package Images;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Paras
 */
public class AHomePg extends javax.swing.JFrame {

    /**
     * Creates new form AHomePg
     */
    public AHomePg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        manageborrower = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        serachbook = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        managestd = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        managebook = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        report = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 111));
        jPanel1.setPreferredSize(new java.awt.Dimension(773, 120));
        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 0, 110, 100);

        jLabel3.setBackground(new java.awt.Color(200, 0, 0));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LIBRARY MANAGEMENT SYSTEM");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(150, 0, 710, 100);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1040, 100);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5), "Admin Panel", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 40))); // NOI18N
        jPanel7.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(0, 0, 111));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(null);

        manageborrower.setBackground(new java.awt.Color(0, 0, 0));
        manageborrower.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        manageborrower.setForeground(new java.awt.Color(255, 255, 255));
        manageborrower.setText("Manage Borrower");
        manageborrower.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageborrowerMouseClicked(evt);
            }
        });
        jPanel3.add(manageborrower);
        manageborrower.setBounds(10, 110, 130, 20);

        jPanel7.add(jPanel3);
        jPanel3.setBounds(40, 260, 150, 140);

        jPanel2.setBackground(new java.awt.Color(0, 0, 111));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(200, 0, 0));
        jPanel4.setLayout(null);
        jPanel2.add(jPanel4);
        jPanel4.setBounds(490, 200, 140, 140);

        serachbook.setBackground(new java.awt.Color(0, 0, 0));
        serachbook.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        serachbook.setForeground(new java.awt.Color(255, 255, 255));
        serachbook.setText(" Search Book");
        jPanel2.add(serachbook);
        serachbook.setBounds(20, 110, 90, 20);

        jPanel7.add(jPanel2);
        jPanel2.setBounds(400, 70, 140, 140);

        jPanel8.setBackground(new java.awt.Color(0, 0, 111));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });
        jPanel8.setLayout(null);

        managestd.setBackground(new java.awt.Color(0, 0, 0));
        managestd.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        managestd.setForeground(new java.awt.Color(255, 255, 255));
        managestd.setText("Manage Member");
        managestd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                managestdMouseClicked(evt);
            }
        });
        jPanel8.add(managestd);
        managestd.setBounds(20, 110, 120, 20);

        jPanel7.add(jPanel8);
        jPanel8.setBounds(40, 70, 150, 140);

        jPanel9.setBackground(new java.awt.Color(0, 0, 111));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
        });
        jPanel9.setLayout(null);

        jPanel10.setBackground(new java.awt.Color(200, 0, 0));
        jPanel10.setLayout(null);
        jPanel9.add(jPanel10);
        jPanel10.setBounds(490, 200, 140, 140);

        managebook.setBackground(new java.awt.Color(0, 0, 0));
        managebook.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        managebook.setForeground(new java.awt.Color(255, 255, 255));
        managebook.setText("Manage Books");
        managebook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                managebookMouseClicked(evt);
            }
        });
        jPanel9.add(managebook);
        managebook.setBounds(20, 110, 110, 20);

        jPanel7.add(jPanel9);
        jPanel9.setBounds(220, 70, 140, 140);

        jPanel13.setBackground(new java.awt.Color(0, 0, 111));
        jPanel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel13MouseClicked(evt);
            }
        });
        jPanel13.setLayout(null);

        jPanel14.setBackground(new java.awt.Color(200, 0, 0));
        jPanel14.setLayout(null);
        jPanel13.add(jPanel14);
        jPanel14.setBounds(490, 200, 140, 140);

        report.setBackground(new java.awt.Color(0, 0, 0));
        report.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        report.setForeground(new java.awt.Color(255, 255, 255));
        report.setText("General Report");
        jPanel13.add(report);
        report.setBounds(20, 110, 110, 20);

        jPanel15.setBackground(new java.awt.Color(200, 0, 0));
        jPanel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel15MouseClicked(evt);
            }
        });
        jPanel15.setLayout(null);

        jPanel16.setBackground(new java.awt.Color(200, 0, 0));
        jPanel16.setLayout(null);
        jPanel15.add(jPanel16);
        jPanel16.setBounds(490, 200, 140, 140);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Manage Books");
        jPanel15.add(jLabel10);
        jLabel10.setBounds(20, 110, 110, 20);

        jPanel13.add(jPanel15);
        jPanel15.setBounds(150, 270, 140, 140);

        jPanel7.add(jPanel13);
        jPanel13.setBounds(220, 260, 140, 140);

        jPanel21.setBackground(new java.awt.Color(0, 0, 111));
        jPanel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel21MouseClicked(evt);
            }
        });
        jPanel21.setLayout(null);

        jPanel22.setBackground(new java.awt.Color(200, 0, 0));
        jPanel22.setLayout(null);
        jPanel21.add(jPanel22);
        jPanel22.setBounds(490, 200, 140, 140);

        logout.setBackground(new java.awt.Color(0, 0, 0));
        logout.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        jPanel21.add(logout);
        logout.setBounds(40, 110, 50, 20);

        jPanel23.setBackground(new java.awt.Color(200, 0, 0));
        jPanel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel23MouseClicked(evt);
            }
        });
        jPanel23.setLayout(null);

        jPanel24.setBackground(new java.awt.Color(200, 0, 0));
        jPanel24.setLayout(null);
        jPanel23.add(jPanel24);
        jPanel24.setBounds(490, 200, 140, 140);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Manage Books");
        jPanel23.add(jLabel14);
        jLabel14.setBounds(20, 110, 110, 20);

        jPanel21.add(jPanel23);
        jPanel23.setBounds(150, 270, 140, 140);

        jPanel25.setBackground(new java.awt.Color(200, 0, 0));
        jPanel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel25MouseClicked(evt);
            }
        });
        jPanel25.setLayout(null);

        jPanel26.setBackground(new java.awt.Color(200, 0, 0));
        jPanel26.setLayout(null);
        jPanel25.add(jPanel26);
        jPanel26.setBounds(490, 200, 140, 140);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Manage Books");
        jPanel25.add(jLabel15);
        jLabel15.setBounds(20, 110, 110, 20);

        jPanel27.setBackground(new java.awt.Color(200, 0, 0));
        jPanel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel27MouseClicked(evt);
            }
        });
        jPanel27.setLayout(null);

        jPanel28.setBackground(new java.awt.Color(200, 0, 0));
        jPanel28.setLayout(null);
        jPanel27.add(jPanel28);
        jPanel28.setBounds(490, 200, 140, 140);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Manage Books");
        jPanel27.add(jLabel16);
        jLabel16.setBounds(20, 110, 110, 20);

        jPanel25.add(jPanel27);
        jPanel27.setBounds(150, 270, 140, 140);

        jPanel21.add(jPanel25);
        jPanel25.setBounds(310, 280, 140, 140);

        jPanel7.add(jPanel21);
        jPanel21.setBounds(400, 260, 140, 140);

        getContentPane().add(jPanel7);
        jPanel7.setBounds(190, 150, 600, 480);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        CManageStudents cManageStudents = new CManageStudents();
      cManageStudents.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        ESearchBook eSearchBook = new ESearchBook();
        eSearchBook.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel9MouseClicked

    private void jPanel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel15MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel15MouseClicked

    private void jPanel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel13MouseClicked

    private void jPanel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel23MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel23MouseClicked

    private void jPanel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel27MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel27MouseClicked

    private void jPanel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel25MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel25MouseClicked

    private void jPanel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel21MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel21MouseClicked

    private void managestdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managestdMouseClicked
            AHomePg.this.dispose();
        CManageStudents CManageStudents = new CManageStudents();
     CManageStudents.setVisible(true);
        
      
        
        
    }//GEN-LAST:event_managestdMouseClicked

    private void managebookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managebookMouseClicked
        // TODO add your handling code here:
        AHomePg.this.dispose();
        DManageBooks DManageBooks = new DManageBooks();
        DManageBooks.setVisible(true);
    }//GEN-LAST:event_managebookMouseClicked

    private void manageborrowerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageborrowerMouseClicked
        // TODO add your handling code here:
         AHomePg.this.dispose();
        FManageBorrowers FManageBorrowers = new FManageBorrowers();
        FManageBorrowers.setVisible(true);
    }//GEN-LAST:event_manageborrowerMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        this.dispose();
        AHomePg AHomePg = new AHomePg();
        AHomePg.setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AHomePg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AHomePg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AHomePg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AHomePg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AHomePg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel managebook;
    private javax.swing.JLabel manageborrower;
    private javax.swing.JLabel managestd;
    private javax.swing.JLabel report;
    private javax.swing.JLabel serachbook;
    // End of variables declaration//GEN-END:variables

    static class setVisible {

        public setVisible() {
        }
    }
}
